version: '3.9'
services:
  backend:
    build: ./backend
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=http://localhost:8080
    ports:
      - "5173:5173"
    depends_on:
      - backend
